changing build phase

diff --git a/ci/azure-pipelines.main.yaml b/ci/azure-pipelines.main.yaml
--- a/ci/azure-pipelines.main.yaml
+++ b/ci/azure-pipelines.main.yaml
@@ -36,7 +36,7 @@ jobs:
       versionSpec: '8.12.0' 
 
   - script: |
-      #sudo npm install -g @angular/cli@7.3.6 && \
+      sudo npm install -g @angular/cli@7.3.6 && \
       sudo chown -R $(whoami):$(id -gn) /home/$(whoami) && \
       npm_output=$(npm install 2>&1)
 
@@ -65,8 +65,20 @@ jobs:
       codeCoverageTool: "cobertura"
       summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
     displayName: "Publish code coverage results"
+
+  - script: |
+      build_output=$(npm run build 2>&1)
+      
+      if [ $? -ne 0 ]; then
+        echo "##vso[task.logissue type=error]There was an error building the angular project.%0D%0ACommand output:%0D%0A${build_output//$'\n'/'%0D%0A'}%0D%0AError CIE0024"
+        echo "##vso[task.complete result=Failed;]"
+        echo "Build Web UI step failed. Output:" >> $(system.defaultWorkingDirectory)/pipeline_errors
+        echo $build_output >> $(system.defaultWorkingDirectory)/pipeline_errors
+        echo "" >> $(system.defaultWorkingDirectory)/pipeline_errors
+      fi
+    displayName: "Build Web UI"
   
-  - template: angular/build.yaml@ci_templates
+  #- template: angular/build.yaml@ci_templates
       
   - template: docker/login.yaml@ci_templates
   
@@ -101,11 +113,4 @@ jobs:
       buildUrl: $(buildUrl)$(Build.BuildId)
       slackWebhook: $(slackBuilds)
   
-  - template: slack/build/failed.yaml@ci_templates
-    parameters:
-      author: $(authorName)
-      repository: $(Build.Repository.Name)
-      branch: $(Build.SourceBranch)
-      commit: $(Build.SourceVersionMessage)
-      buildUrl: $(buildUrl)$(Build.BuildId)
-      slackWebhook: $(slackCIFailed)
+  - template: steps/slack-finish-main.yaml@ci_templates
