Retesting with docker

diff --git a/ci/azure-pipelines.main.yaml b/ci/azure-pipelines.main.yaml
--- a/ci/azure-pipelines.main.yaml
+++ b/ci/azure-pipelines.main.yaml
@@ -40,7 +40,7 @@ stages:
     - template: steps/angular-main.yaml@ci_templates   
 
 - stage: 'ImageBuild'
-  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
+  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
   dependsOn: 'AngularBuild'
   jobs:
   - job:
@@ -48,7 +48,23 @@ stages:
       vmImage: 'ubuntu-latest'  
     steps:  
     - template: misc/nalej-component.yaml@ci_templates 
-    - template: steps/docker-angular-main.yaml@ci_templates
+    #- template: steps/docker-angular-main.yaml@ci_templates
+
+
+    - task: DownloadPipelineArtifact@1
+      inputs:
+        artifactName: web-app
+        downloadPath: $(system.defaultWorkingDirectory)/dist/
+      displayName: Download dist to use in the docker image
+
+    - script: |
+        echo $(ls -a)
+        build_output=$(docker build --no-cache -t mggarc59/web:v0.5.0 -f components/web/Dockerfile.ci .)
+        if [ $? -ne 0 ]; then
+          echo "##vso[task.logissue type=error]There was an error creating the docker image nalej/web:edge.%0D%0ACommand output:%0D%0A${build_output//$'\n'/'%0D%0A'}%0D%0AError CIE0025"
+          echo "##vso[task.complete result=Failed;]"
+        fi
+      displayName: Build the docker images
 
 - stage: 'SlackFinish'
   condition: always()
